name:CI Pipeline

on:
  push:
    branches:[main]

jobs:
  build:
    runs-on:ubuntu-latest

steps:
  - name: Checout code
    uses: actions/checout@v5

  - name: set aup Node.js
    uses: actions/setup-node@v3
    with: 
      node-version: 16

  - name: Install dependecies
    run: npm install

  - name: run tests
    run: npm test